version: "3.8"
services:
  wordpress: 
    image: wordpress-php7.1-apache
    container_name: wordpress1
    restart: always
    ports: 
      - 8080:80
    environment: 
      WORDPRESS_DB_HOST: mysql_db
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "admin123"
      WORDPRESS_DB_PREFIX: "wp_123"
    volumes: 
      - ./html/var/www/html
    networks: 
      wordpress_net:
        aliases: 
          - wordpress_host1
volumes:
  html: {}
networks: 
  wordpress_net: 
    name: database_wordpress_net
    driver: bridge
